# Generated by Django 5.2.1 on 2025-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='user_photos/default-profile.png', null=True, upload_to='user_photos/'),
        ),
    ]
