# Generated by Django 5.2.1 on 2025-06-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='user_photos/default.png', upload_to='user_photos/'),
        ),
    ]
