# Generated by Django 5.2.1 on 2025-06-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0004_plan_is_active_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectedemotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detectedemotion',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='detectedemotion',
            name='photos',
            field=models.ImageField(default=8, upload_to='backoffice_engine/user_upload_photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectedemotion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='backoffice_engine/songs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to='backoffice_engine/user_photos'),
        ),
    ]
