# Generated by Django 5.2.1 on 2025-06-21 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0006_alter_detectedemotion_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedemotion',
            name='photos',
            field=models.ImageField(upload_to='backoffice_engine/user_upload_photo'),
        ),
        migrations.AlterField(
            model_name='detectedemotion',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.song'),
        ),
    ]
