# Generated by Django 5.2.1 on 2025-06-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0007_alter_detectedemotion_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedemotion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user'),
        ),
    ]
