# Generated by Django 5.2.1 on 2025-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0008_alter_detectedemotion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedemotion',
            name='detected_emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
