# Generated by Django 5.2.1 on 2025-06-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0010_alter_detectedemotion_emotion_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='song',
        ),
        migrations.AlterField(
            model_name='detectedemotion',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='backoffice_engine/songs'),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
