# Generated by Django 5.2.1 on 2025-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0012_rename_message_feedback_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='credit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
