# Generated by Django 5.2.1 on 2025-06-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0013_plan_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectedemotion',
            name='user_song',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectedemotion',
            name='detected_emotion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
